### ISSUE TITLE
Incorrect specification for parameterisation of R::rexp

### ISSUE THREAD

**Issue by maj-tki** [teuder/rcpp4everyone_en#10]
Hi, 
On page:
https://teuder.github.io/rcpp4everyone_en/220_dpqr_functions.html#exponential-distribution the R namespace signatures for the xexp functions are not correct. The R namespace version are parameterised in terms of the scale (=1/rate), not the rate.

    library(Rcpp)
    cppFunction('Rcpp::NumericVector rcpp_rexp_1(int n, double rate){
      Rcpp::NumericVector v(n);
      v = Rcpp::rexp(n, rate);
      return v;
    }')

    cppFunction('Rcpp::NumericVector rcpp_rexp_2(int n, double scale){
      Rcpp::NumericVector v(n);

     for(int i = 0; i < n; i++){
       v[i] = R::rexp(scale);
     }
     return v;
    }')

    set.seed(3)
    t1 <- rcpp_rexp_1(1000, 0.2)
    set.seed(3)
    t2 <- rcpp_rexp_2(1000, 0.2)
    # returns false:
    identical(t1, t2)
    set.seed(3)
    t2 <- rcpp_rexp_2(1000, 1/0.2)
    # returns true:
    identical(t1, t2)

Thanks.

**Comment by teuder** [comment]
I corrected the page.
Thank you for your help!
