### ISSUE TITLE
Translation permission

### ISSUE THREAD

**Issue by jywang2016** [teuder/rcpp4everyone_en#12]
Hello Masaki,

Thanks so much for your amazing book. It tells a R user to use Rcpp without a deep dive into the c++.

In my research, I need to implement some numerical algorithms to solve the optimization problems. Rcpp is a better choice than pure R due to its effictive performance. And your book makes the features of Rcpp easy to understand. It is really a great book for the R users even without much background knowledge of C++. Therefore, I wonder if it is possible to translate it into my native language(Chinese) for the sake of more potential R users. If you are willing to grant me the permission, I will try my best to translate the book into Chinese. By the way, the project will also be hosted on the github and organized by the bookdown package for the sake of reading. Some realted examples in Chapters (such as Vector, Matrix, Rcpp Suger) will be completed.

Please kindly let me know if it is possble.

Thanks for you patience and consideration.

Jiangyu

**Comment by teuder** [comment]
Hi Jiangyu,

It is great pleasure to have such offering.
Chinese is one of the language that have biggest population, I welcome your translation!
Please tell me when your work is released.

**Comment by jywang2016** [comment]
Hi Masaki,

Thanks for your permission. 

The project is hosted at https://github.com/jywang2016/rcpp4everyone_cn . Chapters 1~11 were already translated into Chinese. The rest of the book will be completed gradually.

Thanks again for your amazing work.

Jiangyu
