### ISSUE TITLE
fix a typo

### ISSUE THREAD

**Issue by jywang2016** [teuder/rcpp4everyone_en#13]
`push_back` in this line should be `push_front`.
https://github.com/teuder/rcpp4everyone_en/blob/4751b3857b73faaab02d30c8b898c02035e15dc9/170_string.Rmd#L55

**Comment by teuder** [comment]
Thank you for your contribution. I fixed the typo now.
I'm very sorry for my late response, I went business travel for past 2 weeks.

**Comment by jywang2016** [comment]
It does't matter. In fact, I'm also busy with my work, that leads to my slow translation progress 😆  .

Anyway, I will keep to list the possible errors in this issue. I hope this will not bother you (Just forgive me 😛 ).

By the way, the description of `getWeekday` seems to miss Friday(6:Sat should be 6:Fri 7:Sat).
https://github.com/teuder/rcpp4everyone_en/blob/447d1d91153ffdb626b806b98e30200cbc57a3be/180_date.Rmd#L58

Also, the following code block validate it.

``` c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
int rcpp_Date(){
  Date d1(2019,10,11); // Friday
  Rcout << d1.getWeekday() << "\n"; 
  return 0;
}
```

The execution result is 

```r
> rcpp_Date()
6
[1] 0
```
