### ISSUE TITLE
Enabling C++11 (chapter 5.1)

### ISSUE THREAD

**Issue by petermeissner** [teuder/rcpp4everyone_en#14]
I am writing an R package using C++ and it took me quite a long time to really get C++11 features working. 

The usual advice found via web search is  (Rcpp tutorials by Eddelbuettel, your book, elsewhere) is to include a line like: `// [[Rcpp::plugins(cpp11)]]` in you cpp-file and be done. 

I am not sure if this is a personal problem - me and my PC - or maybe a Windows problem. But. I had to include a `Makevars` and a `Makevars.win` file follwoing advice from here: https://kevinushey.github.io/blog/2016/09/14/pitfalls-in-writing-portable-c++98-code/ to make it work using Rtools version 3.5.0.4 (should be not too old, right?). 

In "Writing R Extensions" they state https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-C_002b_002b11-code:

> As from version 3.6.0, R selects a default C++ compiler with options that conform as far as possible42 to C++11: this might not be possible43 and packages which do not specify ‘R (>= 3.6)’ need to explicitly require C++11, hence the rest of this section.

... furthermore ...

> In order to use C++11 code in a package, the package’s Makevars file (or Makevars.win on Windows) should include the line

> `CXX_STD = CXX11`
Compilation and linking will then be done with the C++11 compiler.

> Packages without a src/Makevars or src/Makefile file may specify that they require C++11 for code in the src directory by including ‘C++11’ in the ‘SystemRequirements’ field of the DESCRIPTION file, e.g.

`SystemRequirements: C++11`

So, I basically think that section 5.1 is incomplete and should also advise on either adding C++11 to DESCRIPTION or adding environment variables to the makevars files.

**Comment by teuder** [comment]
Hi @petermeissner 
Thank you very much for proposing the issue.

I confirmed the issue is reproduced in my Windows and added description to my Book about c++11 when building R packages.

https://teuder.github.io/rcpp4everyone_en/050_c++11.html#enabling-c11

I usually do not use Windows, so I did not realized the issue for long time. I'm sure the kind contribution of you can save time from a lot of  people.
