### ISSUE TITLE
Use lists instead of titles on chapter 8

### ISSUE THREAD

**Issue by llrs** [teuder/rcpp4everyone_en#16]
Thanks for the book a nice read (although I am at the chapter 8)

I think that on chapter 8 Vector you misues titles member and static member functions should be list. It will make it easier to read and to navigate

**Comment by teuder** [comment]
Hi, @llrs . I have considered this when I wrote the book, but I prefer current style, because we can see and access each member functions from side panel. Anyway, thank you very mush for your suggestion.
