### ISSUE TITLE
The format problem at Chapter 17

### ISSUE THREAD

**Issue by hope-data-science** [teuder/rcpp4everyone_en#18]
In <https://teuder.github.io/rcpp4everyone_en/190_datetime.html> the titles of getDay, getMonth, getWeekday is not formatted well. There should be a space after "###".

Thank you for the great work to introduce Rcpp to us.

**Comment by hope-data-science** [comment]
About the first sentence of Chapter 19, "When you assign a object" should be "When you assign an object".

**Comment by teuder** [comment]
Hi, @hope-data-science  ! 
Sorry for the late response. I fixed the typo. Thank you for your help.
