### ISSUE TITLE
Example of integrate a c++ library in R

### ISSUE THREAD

**Issue by omarbenites** [teuder/rcpp4everyone_en#2]
Hello Masaki,

Thanks for the bookl, it looks so cool!. 
While reading your book, I recall that some packages( i.e [readxl](https://github.com/tidyverse/readxl) or [plogr](https://github.com/krlmlr/plogr)) integrate/bind C++ libraries in R.  They use  [RapidXML C++](http://rapidxml.sourceforge.net/) library and [plog c++ library](https://github.com/SergiusTheBest/plog) respectively and then wrapp in r-package. Do you know how this work is performed? How Do they include the library in a Rpackage and then How Do they implemented? . If you may create a chapter with a simple c++ library binding in R, it will be awesome.

Thanks in advance.
Omar

**Comment by teuder** [comment]
Hi Omar,

Thank you for the comment.

Integrating C++ library into Rcpp is on my To-Do list.
It's not sure when I can write the chapter, but it will appear in the near future.

**Comment by omarbenites** [comment]
Yeah, that would be awesome!.
