### ISSUE TITLE
Add additional material discussing DateVectors and C++ templates?

### ISSUE THREAD

**Issue by lewinfox** [teuder/rcpp4everyone_en#21]
Hi, thanks so much for writing this book- I've recently been working on my first project with Rcpp and it's been extremely helpful.

There are two areas where I have run into problems in my work that aren't mentioned here: one is the slightly unusual behaviour of `DateVector`s and the other is the fact that template programming doesn't work as I expected.

Specifically:

* `DateVector`s are not vectors of `Date`s, but `double`s (see [related SO question](https://stackoverflow.com/questions/55981439/rcpp-error-comparing-a-datevector-element-with-a-date)). This caught me out and caused some confusion. I think it would be helpful to clarify this in Chapter 16 where it currently says "`Date` is a scalar type corresponding to an element of `DateVector`."
* Template programming requires some extra boilerplate in Rcpp, as per [this Rcpp Gallery example](https://gallery.rcpp.org/articles/rcpp-return-macros/).

I have some notes put together on the first point, and a very brief paragraph on the second point. If you think these could be good additions I'm happy to put together a PR and you can take a look. If so, let me know where you think this extra info would fit in the book.

Thanks!

**Comment by teuder** [comment]
Hi @lewinfox 

Thank you for your suggestion!

I think these 2 points are valuable to add to the book and I really welcome your kind PR.

As you pointed out `DateVector` and also `DatetimeVector` are not `Rcpp::Vector` of `Date` or `Datetime`.
I implicitly express the situation by the word `"corresponding to"`, but I knew nobody would notice my intention. Act\tually, these two classes (`NewDateVector`, `NewDatetimeVector`) were not yet implemented at the timing I wrote the chapter.

I think it is good idea to add a section or paragraph at the top of Chapter 16 and 17, where explaining `DateVector` and `DatetimeVector` is internally `NumericVector` and you can use `getDate()` or `getDatetime()` if you want a `std::vector` of `Date` or `Datetime`.

Regarding templates, I think it is useful for readers to add a new chapter explaining the macro `RCPP_RETURN_VECTOR` and `RCPP_RETURN_MATRIX`. I think the best place for the chapter is next to the Chapter 18 `RObject`, or it may be good to add the explanation as a new section of Chapter 18.


I'm wondering what is the best name for the chapter/section. 

My candidate for now is ... 

- Creating a function that receives various data types.

I appreciate your comments on my idea and looking forward to seeing your PR.

Thank you again.

**Comment by lewinfox** [comment]
Great, OK! I'll put a PR together and we can go from there.

**Comment by lewinfox** [comment]
@teuder I've added material on DateVectors [here](https://github.com/lewinfox/rcpp4everyone_en/tree/lewinfox-dates). I also noticed an issue where duplicated section names had caused links in the sidebar to point to the wrong pages, so I fixed that too.

I need to a do a bit more research on the macros as I'm new to C++ and my knowledge is pretty limited. Shall I raise a PR for the changes made already, or would you rather wait until I've written both sections?
